{
 "title": "CEE Capacity",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_memory", "id": "1", "settings": { "script": "_value - 792576" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Available Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_memory_used", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_memory", "id": "1", "settings": { "script": "_value - 792576" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Used Volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_used_volume",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Available Volume",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_used_volume", "id": "1", "settings": { "script": "_value +13742" }, "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_volume_size", "id": "1", "settings": { "script": "_value + 10240" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total vCPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_vcpu", "id": "1", "settings": { "script": "_value - 168" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Available vCPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_vcpu_used", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_vcpu", "id": "1", "settings": { "script": "_value - 168" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_memory_used", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Volume used by Application",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "13742" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total vCPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_vcpu_used", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Hypervisour Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_hypervisor", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Active Hypervisor Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "active_hypervisors", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "total_volume_size", "id": "1", "settings": { "script": "_value + 10240" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "vm_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "volume_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CEE CICs",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CEE Computes",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}