{
 "title": "SDI Capacity",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rack Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "2" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPOD Count",
   "type": "stat",
   "description": "Count of VPODS",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_vpod_count", "id": "1", "settings": { "script": "_value - 1" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CRU Count",
   "type": "stat",
   "description": "Total CRU Count",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_cru_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EAS Count",
   "type": "stat",
   "description": "Control Switch Count",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_control_sw_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NRU Count",
   "type": "stat",
   "description": "Count of Data Switch",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_data_sw_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Ports Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Enabled",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_enable_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Disabled",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_disable_count", "id": "3", "type": "min" }
     ],
     "timeField": "timestamp"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Total Ports Enabled",
   "type": "stat",
   "description": "Total count of EAS Ports Enabled",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_enable_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Ports Disabled",
   "type": "stat",
   "description": "Total count of Ports Disabled",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_disable_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI CRU Inventory",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 13, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "9000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 3, "y": 11 },
   "options": { "content": "# CRUs in Security VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vpod_data.DC21_Commvault_vPOD DC21-Ashburn",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Security  Inventory",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "2000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 4, "y": 19 },
   "options": { "content": "# CRUs in Nexenta VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vpod_data.Nexenta Storage vPOD DC21 - Ashburn ",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Nexenta Inventory",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "2000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 25 },
   "options": { "content": "# CRUs in CEE VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vpod_data.CEE1 vPOD DC21-Ashburn ",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI CEE  Inventory",
   "type": "table",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 3, "y": 61 },
   "options": { "content": "# Switch Inventory\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Data Switches Inventory",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "2000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Control Switches Inventory",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}