{
 "title": "SDI Capacity",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rack Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "2" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CRU Count",
   "type": "stat",
   "description": "Total CRU Count",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_cru_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EAS Count",
   "type": "stat",
   "description": "Control Switch Count",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_control_sw_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "NRU Count",
   "type": "stat",
   "description": "Count of Data Switch",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_data_sw_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VPOD Count",
   "type": "stat",
   "description": "Count of VPODS",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sdi_vpod_count", "id": "1", "settings": { "script": "_value - 1" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Ports Enabled",
   "type": "stat",
   "description": "Total count of EAS Ports Enabled",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_enable_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Ports Disabled",
   "type": "stat",
   "description": "Total count of Ports Disabled",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "ports_disable_count", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI CRU Inventory",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 5 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 7, "y": 11 },
   "options": { "content": "# CRUs in Security VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "4" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Security  Inventory",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 7, "y": 19 },
   "options": { "content": "# CRUs in Nexenta VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "2" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Nexenta Inventory",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 7, "y": 25 },
   "options": { "content": "# CRUs in CEE VPOD\n\n  " },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Allocated CRU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "settings": { "script": "38" }, "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI CEE  Inventory",
   "type": "table",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SDI Data Switches Inventory",
   "type": "table",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "1000" }, "type": "raw_data" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}